
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/client.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.5.0
 * Query Engine version: 280c870be64f457428992c43c1f6d557fab6e29e
 */
Prisma.prismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes




  const path = require('path')

/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminsScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  masterid: 'masterid'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};


exports.Prisma.ModelName = {
  admins: 'admins'
};
/**
 * Create the Client
 */
const config = {
  "previewFeatures": [],
  "clientVersion": "7.5.0",
  "engineVersion": "280c870be64f457428992c43c1f6d557fab6e29e",
  "activeProvider": "postgresql",
  "inlineSchema": "generator client {\n  provider = \"prisma-client-js\"\n  output   = \"../prisma-client-admin\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\nmodel admins {\n  id       Int     @id @default(autoincrement())\n  email    String  @unique @db.VarChar\n  password String  @db.VarChar\n  masterid Boolean @default(false)\n}\n"
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"admins\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"email\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"password\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"masterid\",\"kind\":\"scalar\",\"type\":\"Boolean\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.parameterizationSchema = {
  strings: JSON.parse("[\"where\",\"admins.findUnique\",\"admins.findUniqueOrThrow\",\"orderBy\",\"cursor\",\"admins.findFirst\",\"admins.findFirstOrThrow\",\"admins.findMany\",\"data\",\"admins.createOne\",\"admins.createMany\",\"admins.createManyAndReturn\",\"admins.updateOne\",\"admins.updateMany\",\"admins.updateManyAndReturn\",\"create\",\"update\",\"admins.upsertOne\",\"admins.deleteOne\",\"admins.deleteMany\",\"having\",\"_count\",\"_avg\",\"_sum\",\"_min\",\"_max\",\"admins.groupBy\",\"admins.aggregate\",\"AND\",\"OR\",\"NOT\",\"id\",\"email\",\"password\",\"masterid\",\"equals\",\"not\",\"in\",\"notIn\",\"lt\",\"lte\",\"gt\",\"gte\",\"contains\",\"startsWith\",\"endsWith\",\"set\",\"increment\",\"decrement\",\"multiply\",\"divide\"]"),
  graph: "MAsQBxwAACUAMB0AAAQAEB4AACUAMB8CAAAAASABAAAAASEBACcAISIgACgAIQEAAAABACABAAAAAQAgBxwAACUAMB0AAAQAEB4AACUAMB8CACYAISABACcAISEBACcAISIgACgAIQADAAAABAAgAwAABQAwBAAAAQAgAwAAAAQAIAMAAAUAMAQAAAEAIAMAAAAEACADAAAFADAEAAABACAEHwIAAAABIAEAAAABIQEAAAABIiAAAAABAQgAAAkAIAQfAgAAAAEgAQAAAAEhAQAAAAEiIAAAAAEBCAAACwAwAQgAAAsAMAQfAgAwACEgAQAuACEhAQAuACEiIAAvACECAAAAAQAgCAAADgAgBB8CADAAISABAC4AISEBAC4AISIgAC8AIQIAAAAEACAIAAAQACACAAAABAAgCAAAEAAgAwAAAAEAIA8AAAkAIBAAAA4AIAEAAAABACABAAAABAAgBRUAACkAIBYAACoAIBcAAC0AIBgAACwAIBkAACsAIAccAAAaADAdAAAXABAeAAAaADAfAgAbACEgAQAcACEhAQAcACEiIAAdACEDAAAABAAgAwAAFgAwFAAAFwAgAwAAAAQAIAMAAAUAMAQAAAEAIAccAAAaADAdAAAXABAeAAAaADAfAgAbACEgAQAcACEhAQAcACEiIAAdACENFQAAHwAgFgAAJAAgFwAAHwAgGAAAHwAgGQAAHwAgIwIAAAABJAIAIwAhJQIAAAAEJgIAAAAEJwIAAAABKAIAAAABKQIAAAABKgIAAAABDhUAAB8AIBgAACIAIBkAACIAICMBAAAAASQBACEAISUBAAAABCYBAAAABCcBAAAAASgBAAAAASkBAAAAASoBAAAAASsBAAAAASwBAAAAAS0BAAAAAQUVAAAfACAYAAAgACAZAAAgACAjIAAAAAEkIAAeACEFFQAAHwAgGAAAIAAgGQAAIAAgIyAAAAABJCAAHgAhCCMCAAAAASQCAB8AISUCAAAABCYCAAAABCcCAAAAASgCAAAAASkCAAAAASoCAAAAAQIjIAAAAAEkIAAgACEOFQAAHwAgGAAAIgAgGQAAIgAgIwEAAAABJAEAIQAhJQEAAAAEJgEAAAAEJwEAAAABKAEAAAABKQEAAAABKgEAAAABKwEAAAABLAEAAAABLQEAAAABCyMBAAAAASQBACIAISUBAAAABCYBAAAABCcBAAAAASgBAAAAASkBAAAAASoBAAAAASsBAAAAASwBAAAAAS0BAAAAAQ0VAAAfACAWAAAkACAXAAAfACAYAAAfACAZAAAfACAjAgAAAAEkAgAjACElAgAAAAQmAgAAAAQnAgAAAAEoAgAAAAEpAgAAAAEqAgAAAAEIIwgAAAABJAgAJAAhJQgAAAAEJggAAAAEJwgAAAABKAgAAAABKQgAAAABKggAAAABBxwAACUAMB0AAAQAEB4AACUAMB8CACYAISABACcAISEBACcAISIgACgAIQgjAgAAAAEkAgAfACElAgAAAAQmAgAAAAQnAgAAAAEoAgAAAAEpAgAAAAEqAgAAAAELIwEAAAABJAEAIgAhJQEAAAAEJgEAAAAEJwEAAAABKAEAAAABKQEAAAABKgEAAAABKwEAAAABLAEAAAABLQEAAAABAiMgAAAAASQgACAAIQAAAAAAAS4BAAAAAQEuIAAAAAEFLgIAAAABLwIAAAABMAIAAAABMQIAAAABMgIAAAABAAAAAAUVAAYWAAcXAAgYAAkZAAoAAAAAAAUVAAYWAAcXAAgYAAkZAAoBAgECAwEFBgEGBwEHCAEJCgEKDAILDQMMDwENEQIOEgQREwESFAETFQIaGAUbGQs"
}
config.compilerWasm = {
      getRuntime: async () => require('./query_compiler_fast_bg.js'),
      getQueryCompilerWasmModule: async () => {
        const { Buffer } = require('node:buffer')
        const { wasm } = require('./query_compiler_fast_bg.wasm-base64.js')
        const queryCompilerWasmFileBytes = Buffer.from(wasm, 'base64')

        return new WebAssembly.Module(queryCompilerWasmFileBytes)
      },
      importName: './query_compiler_fast_bg.js',
    }

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
